// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBJOx4lkvcKnZCbMECSa6Wxnw4iGj37lDc',
    appId: '1:781228422790:web:0c9aebea45cd2d861d0307',
    messagingSenderId: '781228422790',
    projectId: 'atlas-messenger-488106',
    authDomain: 'atlas-messenger-488106.firebaseapp.com',
    storageBucket: 'atlas-messenger-488106.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD67ccWPzUzrB_CRwIaKiurvAwJ4dfSK88',
    appId: '1:781228422790:ios:1917140eeac5706f1d0307',
    messagingSenderId: '781228422790',
    projectId: 'atlas-messenger-488106',
    storageBucket: 'atlas-messenger-488106.firebasestorage.app',
    androidClientId: '781228422790-8gehfs9p2gn6mg9e6g2jd98gf0s6quer.apps.googleusercontent.com',
    iosBundleId: 'com.example.myApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD67ccWPzUzrB_CRwIaKiurvAwJ4dfSK88',
    appId: '1:781228422790:ios:1917140eeac5706f1d0307',
    messagingSenderId: '781228422790',
    projectId: 'atlas-messenger-488106',
    storageBucket: 'atlas-messenger-488106.firebasestorage.app',
    androidClientId: '781228422790-8gehfs9p2gn6mg9e6g2jd98gf0s6quer.apps.googleusercontent.com',
    iosBundleId: 'com.example.myApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBJOx4lkvcKnZCbMECSa6Wxnw4iGj37lDc',
    appId: '1:781228422790:web:09c44955098bc9b91d0307',
    messagingSenderId: '781228422790',
    projectId: 'atlas-messenger-488106',
    authDomain: 'atlas-messenger-488106.firebaseapp.com',
    storageBucket: 'atlas-messenger-488106.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAoMgnsh-cSkiXYPSnoLME2RWZMnjEzB_M',
    appId: '1:781228422790:android:af25c3e37c8eb2361d0307',
    messagingSenderId: '781228422790',
    projectId: 'atlas-messenger-488106',
    storageBucket: 'atlas-messenger-488106.firebasestorage.app',
  );

}